options {
   STATIC=false;
   SANITY_CHECK=true;
   DEBUG_PARSER=false;
   DEBUG_TOKEN_MANAGER=false;
}

PARSER_BEGIN(ProtoParser)

package org.infinispan.protostream.impl.parser;

import java.io.Reader;import java.util.regex.Pattern;
import org.infinispan.protostream.descriptors.Label;

/**
 * Protocol Buffers grammar  for JavaCC
 * Based on ProtoParser.jjt by Toshikazu Ando (foobar@em.boo.jp)
 * @see "https://developers.google.com/protocol-buffers/docs/proto3"
 */
public class ProtoParser {
   static final Pattern DECOMMENTIFY = Pattern.compile("(\\s*\\*+\\/|^([ \\t]*\\/\\*+|[ \\t]*\\*[ \\t]*))", Pattern.MULTILINE);

   static ProtoFile parse(String fileName, Reader reader) throws ParseException {
      ProtoFile f = new ProtoParser(reader).Input();
      f.fileName(fileName);
      return f;
   }

   static void appendComment(StringBuilder s) {
      ProtoFile.comments.get().append(s);
   }

   static String comment() {
      String s = ProtoFile.comments.get().toString();
      ProtoFile.comments.remove();
      return DECOMMENTIFY.matcher(s).replaceAll("").trim();
   }

   static String unquote(String s) {
      return s.charAt(0) == '"' ? s.substring(1, s.length() - 1) : s;
   }

   static String unquote(Token t) {
      return unquote(t.image);
   }

   static int toInt(Token t) {
      return Integer.parseInt(t.image);
   }
}

PARSER_END(ProtoParser)

SKIP :
{
  " "
| "\t"
| "\n"
| "\r"
| <"//" (~["\n","\r"])* ("\n" | "\r" | "\r\n")> { ProtoParser.appendComment(image); }
| <"/*" (~["*"])* "*" ("*" | ~["*","/"] (~["*"])* "*")* "/"> { ProtoParser.appendComment(image); }
}


TOKEN :
{
  <CSTRING_TKN: "\"" ( ~["\""] )* "\"" >
| <EQUL_TKN: "=">
| <SEMI_COLON_TKN: ";">
| <COLON_TKN: ":">
| <COMMA_TKN: ",">
| <DOT_TKN: ".">
| <TO_TKN: "to">
| <LEFTBRACE_TKN: "{">
| <RIGHTBRACE_TKN: "}">
| <LEFTPAREN_TKN: "(">
| <RIGHTPAREN_TKN: ")">
| <LEFTBRACKET_TKN: "[">
| <RIGHTBRACKET_TKN: "]">
| <LESSTHAN_TKN: "<">
| <GRATETHAN_TKN: ">">
| <SYNTAX_TKN: "syntax">
| <BOOLEAN_TKN: "true" | "false">
| <ATTRIBUTE_TKN: "required"
                | "optional"
                | "repeated">
| <OPTION_TKN: "option">
| <IMPORT_TKN: "import">
| <PUBLIC_TKN: "public">
| <PACKAGE_TKN: "package">
| <SERVICE_TKN: "service">
| <MESSAGE_TKN: "message">
| <ENUM_TKN: "enum">
| <ONEOF_TKN: "oneof">
| <GROUP_TKN: "group">
| <EXTENTIONS_TKN: "extensions">
| <EXTEND_TKN: "extend">
| <MAP_TKN: "map">
| <RESERVED_TKN: "reserved">
| <RETURNS_TKN: "returns">
| <STREAM_TKN: "stream">
| <RPC_TKN: "rpc">
| <NUMBER_TKN: "0" | (["-"])?["1"-"9"](["0"-"9"])* | "max">
| <DOUBLE_TKN: ("0" | (["-"])?["1"-"9"](["0"-"9"])*) "." (["0"-"9"])*>
| <IDENT_TKN: ["_","a"-"z","A"-"Z"] (["_","a"-"z","A"-"Z","0"-"9"])*>
}

ProtoFile Input() : {
   ProtoFile p = new ProtoFile();
} {
  (SyntaxPart(p) { p.documentation(comment()); })?
  (ImportPart(p) { p.documentation( p.documentation() + comment()); }
   | OptionPart(p)
   | PackagePart(p)
   | ServicePart(p)
   | MessagePart(p, p.packageName())
   | EnumPart(p, p.packageName())
   | ExtendPart(p, p.packageName()))*
   <EOF>{ return p; }
}

void ImportPart(ProtoFile p) : {
 Token t;
 boolean pub = false;
} {
  <IMPORT_TKN> [<PUBLIC_TKN> { pub = true; }] t = <CSTRING_TKN> <SEMI_COLON_TKN> { if (pub) p.addPublicImport(unquote(t)); else p.addPrivateImport(unquote(t)); }
}


String ValuePart() : {
    Token t;
} {
  t = <BOOLEAN_TKN> { return t.image; }
   | t = <CSTRING_TKN> { return t.image; }
   | t = <NUMBER_TKN>  { return t.image; }
   | t = <DOUBLE_TKN> { return t.image; }
   | t = <IDENT_TKN> { return t.image; }
   | BraceValuePart() { return null; /*TODO*/ }
}

void BraceValuePart() : {
} {
   <LEFTBRACE_TKN>
   (BraceValueOnePart())*
   <RIGHTBRACE_TKN>
}
void BraceValueOnePart() : {
} {
   <IDENT_TKN> <COLON_TKN> (BraceValueOneBracketPart() | ValuePart())
}
void BraceValueOneBracketPart() : {
} {
   <LEFTBRACKET_TKN>
   ValuePart() (<COMMA_TKN> ValuePart())*
   <RIGHTBRACKET_TKN>
}
void SyntaxPart(ProtoFile p) : {
   Token t;
} {
   <SYNTAX_TKN> <EQUL_TKN> t=<CSTRING_TKN> <SEMI_COLON_TKN> { p.syntax(ProtoFile.Syntax.valueOf(unquote(t))); }
}
void OptionPart(OptionsContainer o) : {
   String name;
   String value;
} {
    <OPTION_TKN> name=ClassPart() <EQUL_TKN> value=ValuePart() <SEMI_COLON_TKN> { o.addOption(new OptionElement(name, value)); }
}
String ClassPart() : {
   StringBuilder sb = new StringBuilder();
   String s;
   Token t;
} {
  ( t = <IDENT_TKN> { sb.append(t.image); } | s = CustomOptionsPart() { sb.append(s); } ) (<DOT_TKN> { sb.append('.'); } ( t = <IDENT_TKN> { sb.append(t.image); } | s = CustomOptionsPart() { sb.append(s); }))* { return sb.toString(); }
}
String CustomOptionsPart() : {
   String s;
} {
   <LEFTPAREN_TKN> s = ClassPart() <RIGHTPAREN_TKN> { return s; }
}
String KeyPart() : {
    Token t;
} {
   t = <IDENT_TKN> { return t.image; }
    | t = <MESSAGE_TKN> { return t.image; }
    | t = <PACKAGE_TKN> { return t.image; }
    | t = <SERVICE_TKN> { return t.image; }
}

void PackagePart(ProtoFile p) : {
 String s;
} {
  <PACKAGE_TKN> s = ClassPart() <SEMI_COLON_TKN> { p.packageName(s); }
}

void ServicePart(ProtoFile p) : {
} {
  <SERVICE_TKN> <IDENT_TKN>
   <LEFTBRACE_TKN>
   (OptionPart(p)
    |RpcPart())*
   <RIGHTBRACE_TKN>
}
void RpcPart() : {
} {
  <RPC_TKN> ClassPart()
   <LEFTPAREN_TKN>
   [(StreamPart())? ClassPart()]
   <RIGHTPAREN_TKN>
   <RETURNS_TKN>

   <LEFTPAREN_TKN>
   [(StreamPart())? ClassPart()]
   <RIGHTPAREN_TKN>

   (RpcBracePart()|<SEMI_COLON_TKN>)
}
void StreamPart() : {
} {
    <STREAM_TKN>
}
void RpcBracePart() : {
} {
    <LEFTBRACE_TKN>
    (OptionPart(null))*
    <RIGHTBRACE_TKN>
}

void MessagePart(MessageContainer c, String prefix) : {
 MessageElement m = new MessageElement().documentation(comment());
 String s;
} {
  <MESSAGE_TKN> s = ClassPart() { m.name(s).prefix(prefix); } MessageBranchPart(m) { c.addMessage(m); }
}
void MessageBranchPart(MessageElement m) : {
 FieldElement f;
} {
   <LEFTBRACE_TKN>
   (FieldPart(m)
    |EnumPart(m, m.qualifiedName())
    |ReservedPart(m)
    |OneOfPart(m)
    |MapPart(m)
    |MessagePart(m, m.qualifiedName())
    |ExtensionsPart(m)
    |ExtendPart(m, m.qualifiedName())
    |OptionPart(m)
    |<SEMI_COLON_TKN>)*
   <RIGHTBRACE_TKN>
}
FieldElement FieldPart(FieldContainer c) : {
 FieldElement f = new FieldElement().documentation(comment());
 Token t;
} {
  [t = <ATTRIBUTE_TKN> { f.label(Label.valueOf(t.image.toUpperCase())); }]
  MemberPart(f) { c.addField(f); return f; }
}
void MemberPart(FieldElement f) : {
 String s;
 Token t;
 DataType dt;
} {
  dt = TypePart() s = KeyPart() { f.type(dt); f.name(s); } <EQUL_TKN> t = <NUMBER_TKN> { f.tag(toInt(t)); } [FieldOptionsPart(f)] <SEMI_COLON_TKN>
}
DataType TypePart() : {
    Token t;
} {
  t = <IDENT_TKN> { return DataType.create(t.image); }
}
void FieldOptionsPart(OptionsContainer o) : {
} {
  <LEFTBRACKET_TKN>
  (FieldOptionPart(o) (<COMMA_TKN> FieldOptionPart(o))*)?
  <RIGHTBRACKET_TKN>
}
void FieldOptionPart(OptionsContainer o) : {
   String n, v;
} {
  n = ClassPart() <EQUL_TKN> v = ValuePart() { o.addOption(new OptionElement(n, unquote(v))); }
}

void EnumPart(EnumContainer enumContainer, String prefix) : {
   EnumElement e = new EnumElement().documentation(comment());
   String s;
} {
  <ENUM_TKN>
   s = ClassPart() { e.name(s).prefix(prefix); }
   <LEFTBRACE_TKN>
   (OptionPart(e))*
   (EnumMemberPart(e))*
   <RIGHTBRACE_TKN>
   { enumContainer.addEnum(e); }
}
void EnumMemberPart(EnumElement e) : {
   String n;
   Token t;
} {
  n = ClassPart() <EQUL_TKN> t = <NUMBER_TKN> [FieldOptionsPart(e)] <SEMI_COLON_TKN> { e.addEnumConstant(new EnumConstantElement(n, toInt(t)).documentation(comment())); }
}

void ReservedPart(MessageElement m) : {
} {
  <RESERVED_TKN> ReservedValuesPart(m)
}

void ReservedValuesPart(MessageElement m) : {
   Token t;
}
{
   t = <CSTRING_TKN> { m.addReserved(unquote(t)); } ( <COMMA_TKN> t = <CSTRING_TKN> { m.addReserved(unquote(t)); } )* <SEMI_COLON_TKN>
   | ReservedNumberPart(m) (<COMMA_TKN> ReservedNumberPart(m) )* <SEMI_COLON_TKN>
}

void ReservedNumberPart(MessageElement m) : {
   Token t1, t2 = null;
}
{
   t1 = <NUMBER_TKN> ( <TO_TKN> t2 = <NUMBER_TKN> )?
   {
      if (t2 == null) {
         m.addReserved(toInt(t1));
      } else {
         m.addReserved(toInt(t1), toInt(t2));
      }
   }
}

void OneOfPart(MessageElement m) : {
   OneOfElement oneof = new OneOfElement().documentation(comment());
   FieldElement f;
   String s;
} {
  <ONEOF_TKN>
   s = ClassPart() { oneof.name(s); }
   <LEFTBRACE_TKN>
   ( { f = new FieldElement().label(Label.ONE_OF); } MemberPart(f) { oneof.addField(f); })*
   <RIGHTBRACE_TKN>
   { m.addOneOf(oneof); }
}

void MapPart(FieldContainer c) : {
   DataType kt, vt;
   String n;
   Token t;
   FieldElement f = new FieldElement();
} {

  <MAP_TKN>
  <LESSTHAN_TKN>
   kt = TypePart()
   <COMMA_TKN>
   vt = TypePart()
  <GRATETHAN_TKN>
  n = KeyPart() <EQUL_TKN> t = <NUMBER_TKN> <SEMI_COLON_TKN> { f.name(n).type(DataType.create(kt, vt)).tag(toInt(t)); c.addField(f);  }
}

void ExtensionsPart(MessageElement m) : {
   Token t1, t2;
} {
  <EXTENTIONS_TKN> t1 = <NUMBER_TKN> <TO_TKN> t2 = <NUMBER_TKN> <SEMI_COLON_TKN> { m.addExtensions(toInt(t1), toInt(t2)); }
}

void ExtendPart(MessageContainer m, String prefix) : {
   ExtendElement e;
   FieldElement f;
   String s;
} {
  <EXTEND_TKN> s = ClassPart() { e = new ExtendElement().name(s).prefix(prefix).documentation(comment()); } <LEFTBRACE_TKN> (f = FieldPart(e) )+ <RIGHTBRACE_TKN> { m.addExtend(e); }
}
/* END */
