options {
   STATIC=false;
   SANITY_CHECK=true;
   DEBUG_PARSER=false;
   DEBUG_TOKEN_MANAGER=false;
}

PARSER_BEGIN(Proto3Parser)

package org.infinispan.protostream.impl.parser;

import java.io.Reader;
import java.util.regex.Pattern;
import org.infinispan.protostream.descriptors.Descriptor;
import org.infinispan.protostream.descriptors.EnumContainer;
import org.infinispan.protostream.descriptors.EnumDescriptor;
import org.infinispan.protostream.descriptors.EnumValueDescriptor;
import org.infinispan.protostream.descriptors.FieldContainer;
import org.infinispan.protostream.descriptors.FieldDescriptor;
import org.infinispan.protostream.descriptors.FileDescriptor;
import org.infinispan.protostream.descriptors.Label;
import org.infinispan.protostream.descriptors.MessageContainer;
import org.infinispan.protostream.descriptors.OneOfDescriptor;
import org.infinispan.protostream.descriptors.Option;
import org.infinispan.protostream.descriptors.OptionContainer;
import org.infinispan.protostream.descriptors.ReservedContainer;

/**
* <a href="https://protobuf.dev/reference/protobuf/proto3-spec/">Protocol Buffers 3</a> parser.
*/
public class Proto3Parser {
   static final Pattern DECOMMENTIFY = Pattern.compile("(\\s*\\*+\\/|^([ \\t]*\\/\\*+|[ \\t]*\\*[ \\t]*))", Pattern.MULTILINE);

   static FileDescriptor parse(String fileName, Reader reader) throws ParseException {
      FileDescriptor.Builder f = new Proto3Parser(reader).Proto();
      f.withName(fileName);
      return f.build();
   }

   static void appendComment(StringBuilder s) {
      ProtoFile.comments.get().append(s);
   }

   static String comment() {
      String s = ProtoFile.comments.get().toString();
      ProtoFile.comments.remove();
      return DECOMMENTIFY.matcher(s).replaceAll("").trim();
   }

   static String unquote(String s) {
      return s.charAt(0) == '"' ? s.substring(1, s.length() - 1) : s;
   }

   static String unquote(Token t) {
      return unquote(t.image);
   }

   static int toInt(Token t) {
      return Integer.parseInt(t.image);
   }
}

PARSER_END(Proto3Parser)

<*> SKIP :
{
  " "
| "\t"
| "\n"
| "\r"
| <"//" (~["\n","\r"])* ("\n" | "\r" | "\r\n")> { Proto3Parser.appendComment(image); }
| <"/*" (~["*"])* "*" ("*" | ~["*","/"] (~["*"])* "*")* "/"> { Proto3Parser.appendComment(image); }
}


<DEFAULT> TOKEN :
{
  <STRLIT: "\"" ( ~["\""] )* "\"" >
| <EQ: "=">
| <SEMI_COLON: ";">
| <COLON: ":">
| <COMMA: ",">
| <DOT: ".">
| <TO: "to">
| <LBRACE: "{">
| <RBRACE: "}">
| <LPAREN: "(">
| <RPAREN: ")">
| <LBRACKET: "[">
| <RBRACKET: "]">
| <LT: "<">
| <GT: ">">
| <SYNTAX: "syntax">
| <BOOLEAN: "true" | "false">
| <ATTRIBUTE: "required"
            | "optional"
            | "repeated"> : IDSTATE
| <OPTION: "option"> : OPTSTATE
| <IMPORT: "import">
| <PUBLIC: "public">
| <WEAK: "weak">
| <PACKAGE: "package"> : IDSTATE
| <SERVICE: "service">
| <MESSAGE: "message"> : IDSTATE
| <ENUM: "enum"> : IDSTATE
| <ONEOF: "oneof"> : IDSTATE
| <GROUP: "group">
| <EXTENSIONS: "extensions">
| <EXTEND: "extend">
| <MAP: "map"> : IDSTATE
| <RESERVED: "reserved">
| <RETURNS: "returns">
| <STREAM: "stream">
| <RPC: "rpc">
| <NUMBER: "0" | (["-"])?["1"-"9"](["0"-"9"])* | "max">
| <DOUBLE: ("0" | (["-"])?["1"-"9"](["0"-"9"])*) "." (["0"-"9"])*>
}

<DEFAULT, IDSTATE> TOKEN : {
  <IDENT: ["_","a"-"z","A"-"Z"] (["_","a"-"z","A"-"Z","0"-"9"])*> : DEFAULT
| <FULLIDENT: ["_","a"-"z","A"-"Z"] (["_","a"-"z","A"-"Z","0"-"9"])* ("." ["_","a"-"z","A"-"Z"] (["_","a"-"z","A"-"Z","0"-"9"])*)+ > : DEFAULT
}

<OPTSTATE> TOKEN : {
   <OPTIONNAME: ["_","a"-"z","A"-"Z"] (["_","a"-"z","A"-"Z","0"-"9"])* ("." ["_","a"-"z","A"-"Z"] (["_","a"-"z","A"-"Z","0"-"9"])*)+ > : DEFAULT
}

FileDescriptor.Builder Proto() : {
    FileDescriptor.Builder f = new FileDescriptor.Builder();
}
{
    [ Syntax(f) ] (Import(f) | Package(f) | Option(f) | TopLevelDef(f) | EmptyStatement() )+ <EOF> { return f; }
}

void EmptyStatement() : {}
{
    <SEMI_COLON>
}

void TopLevelDef(FileDescriptor.Builder f) : {}
{
    Message(f) | Enum(f) | Service(f)
}

void Syntax(FileDescriptor.Builder f) : {
    Token t;
}
{
    <SYNTAX> <EQ> t = <STRLIT> <SEMI_COLON> { f.withSyntax(FileDescriptor.Syntax.fromString(unquote(t))); }
}

void Import(FileDescriptor.Builder f) : {
    boolean pub = false;
    Token t;
}
{
    <IMPORT> [ <WEAK> | <PUBLIC> { pub = true; } ] t = <STRLIT> <SEMI_COLON> { if (pub) f.addPublicDependency(t.image); else f.addDependency(t.image); }
}

void Package(FileDescriptor.Builder f) : {
    Token t;
}
{
    <PACKAGE> ( t = <IDENT> | t = <FULLIDENT>) <SEMI_COLON> { f.withPackageName(t.image); }
}

void Option(OptionContainer o) : {}
{
    <OPTION> <OPTIONNAME>  <EQ> Constant() <SEMI_COLON>
}

void Enum(EnumContainer c) : {
   EnumDescriptor.Builder e = new EnumDescriptor.Builder();
   String name;
}
{
    <ENUM> name = EnumName() EnumBody(e) { c.addEnum(e.withName(name).build()); }
}

void EnumBody(EnumDescriptor.Builder e) : {}
{
    <LBRACE> ( Option(e) | EnumField(e) | EmptyStatement() | Reserved(e) )+ <RBRACE>
}

void EnumField(EnumDescriptor.Builder e) : {
   EnumValueDescriptor.Builder v = new EnumValueDescriptor.Builder();
   Token t;
}
{
    t = <IDENT> { v.withName(t.image); }<EQ> t = <NUMBER> { v.withTag(toInt(t)); } [ <LBRACKET> EnumValueOption(v) ( <COMMA> EnumValueOption(v) )+ <RBRACKET> ] { e.addValue(v.build()); }
}

void EnumValueOption(OptionContainer c) : {
   Token name;
   String value;
}
{
    name = <OPTIONNAME> <EQ> value = Constant() { c.addOption(new Option(name.image, value)); }
}

void Field(FieldContainer c) : {
   FieldDescriptor.Builder f = new FieldDescriptor.Builder();
   Token label;
   Token name;
   Token number;
}
{
    [ label = <ATTRIBUTE> { f.withLabel(Label.fromString(label.image)); } ] Type() name = <IDENT> <EQ> number = <NUMBER> [ <LBRACKET> FieldOptions(f) <RBRACKET> ] <SEMI_COLON> { c.addField(f.withName(name.image).withNumber(toInt(number)).build()); }
}

void FieldOptions(OptionContainer c) : {}
{
    FieldOption(c) ( <COMMA> FieldOption(c) )*
}

void FieldOption(OptionContainer c) : {}
{
    <OPTIONNAME> <EQ> Constant()
}

void MapField(Descriptor.Builder m) : {}
{
    <MAP> <LT> KeyType() <COMMA> Type() <GT> MapName() <EQ> <NUMBER> [ <LPAREN> FieldOptions(null) <RPAREN> ] <SEMI_COLON>
}

void KeyType() : {}
{
    Type()
}

void Message(MessageContainer c) : {
   Descriptor.Builder m = new Descriptor.Builder();
   String name;
}
{
    <MESSAGE> name = MessageName() MessageBody(m) { c.addMessage(m.withName(name).build()); }
}

void MessageBody(Descriptor.Builder m) : {}
{
    <LBRACE> ( Field(m) | Enum(m) | Message(m) | Option(m) | OneOf(m) | MapField(m) | Reserved(m) | EmptyStatement() )+ <RBRACE>
}

void MessageValue() : {}
{
    <LBRACE> Message(null) <RBRACE> | <LT> Message(null) <GT>
}

void OneOf(Descriptor.Builder m) : {
   OneOfDescriptor.Builder o = new OneOfDescriptor.Builder();
   String name;
}
{
    <ONEOF> name = OneOfName() <LBRACE> ( Option(m) | OneOfField(o) )+ <RBRACE> { m.addOneOf( o.withName(name).build()); }
}

void OneOfField(OneOfDescriptor.Builder o) : {
   FieldDescriptor.Builder f = new FieldDescriptor.Builder();
   String name;
}
{
    Type() name = FieldName() <EQ> <NUMBER> [ <LBRACKET> FieldOptions(f) <RBRACKET> ] <SEMI_COLON> { o.addField(f.withName(name).build()); }
}

DataType Type() : {
    Token t;
}
{
    (t = <IDENT> | t = <FULLIDENT>) { return DataType.create(t.image); }
}

void Reserved(ReservedContainer c) : {}
{
    <RESERVED> ( Ranges(c) | ReservedNames(c) )+ <SEMI_COLON>
}

void Ranges(ReservedContainer c) : {}
{
    Range(c) ( <COMMA> Range(c) )*
}

void Range(ReservedContainer c) : {}
{
    <NUMBER> [ <TO> <NUMBER> ]
}

void ReservedNames(ReservedContainer c) : {}
{
    <STRLIT> ( <COMMA> <STRLIT> )*
}

void Rpc() : {}
{
    <RPC> RpcName() <LPAREN> [ <STREAM> ] NamedType() <RPAREN> <RETURNS> <LPAREN> [ <STREAM> ] NamedType() <RPAREN> (( <LBRACE> (Option(null) | EmptyStatement() )+ <RBRACE> ) | <SEMI_COLON> )
}

void Service(FileDescriptor.Builder f) : {}
{
    <SERVICE> ServiceName() <LBRACE> (Option(f) | Rpc() | EmptyStatement() )+ <RBRACE>
}

String Constant() : {
   Token t;
}
{
    FullIdent() | t = <NUMBER> { return t.image; } | t = <DOUBLE> { return t.image; } | t = <STRLIT> { return unquote(t); } | t = <BOOLEAN> { return t.image; } | MessageValue() { return null; }
}

String FullIdent() : {
    Token t;
    StringBuilder s = new StringBuilder();
}
{
    t = <IDENT> { s.append(t.image); } ( <DOT> t = <IDENT> { s.append(t.image); } )* { return s.toString(); }
}

String MessageName() : {
    Token t;
}
{
    t = <IDENT> { return t.image; }
}

String EnumName() : {
    Token t;
}
{
    t = <IDENT> { return t.image; }
}

String FieldName() : {
    Token t;
}
{
    t = <IDENT> { return t.image; }
}

String OneOfName() : {
    Token t;
}
{
    t = <IDENT> { return t.image; }
}

String MapName() : {
    Token t;
}
{
    t = <IDENT> { return t.image; }
}

String ServiceName() : {
    Token t;
}
{
    t = <IDENT> { return t.image; }
}

String RpcName() : {
    Token t;
}
{
    t = <IDENT> { return t.image; }
}

String NamedType() : {
    Token t;
    StringBuilder sb = new StringBuilder();
}
{
    t = <IDENT> { sb.append(t.image); } ( <DOT> t = <IDENT> { sb.append('.').append(t.image); } )* { return sb.toString(); }
}

